### ISSUE TITLE
[Suggestion] AutoRegister Toggle

### ISSUE THREAD

**Issue by StpNex** [Tsuser1/Modern-LWC#104]
**Detailed description of problem:**

Let people choose if they want to automatically register blocks, some people love the feature to automatically register all blocks, but some dont, I think this could be a nice addition.

**Comment by chbohn** [comment]
Currently you can make locking blocks optional by removing the line with autoRegister on it for the block in the core config. The default settings currently has a mix. Although I'm guessing that's not what you mean.

This sounds like a good addition, but the only problem right now is that LWC does not keep track of any per-user settings. Everything is with respect to individual protections. This would need to be added before supporting anything like this. Maybe something akin to how Essentials stores user specific data.

I'll leave this as "open to pr" for now.

**Comment by pop4959** [comment]
Currently you can make locking blocks optional by removing the line with autoRegister on it for the block in the core config. The default settings currently has a mix. Although I'm guessing that's not what you mean.

This sounds like a good addition, but the only problem right now is that LWC does not keep track of any per-user settings. Everything is with respect to individual protections. This would need to be added before supporting anything like this. Maybe something akin to how Essentials stores user specific data.

I'll leave this as "open to pr" for now.

**Comment by pop4959** [comment]
I thought about this a bit more. I realised that this feature is probably too much work to implement given how little it provides. On my server, I have never had a player request something like this in the years I've been running it.

The best solution here, is if you or your players are really that picky about the auto registration, just disable it entirely and allow people to /lock each protection. Now, I don't necessarily recommend this, but it's either that, or making people who don't like auto registered protections /unlock things that they don't want automatically registered.

Modifying your core configuration to only auto register blocks that should be auto registered is also a good step to take.
