### ISSUE TITLE
Everyone can open locked things

### ISSUE THREAD

**Issue by BrianmSK** [Tsuser1/Modern-LWC#107]
**LWC Version (/lwc admin version):**  2.1.2
**Server version (/version):** 1.13.2

**Short five word summary of issue:**  Even after locking things up other players can open it

**Detailed description of problem:** Hello i have a problem that when im trying to anyhow lock items on my server it just doesnt work, it says its locked but everyone can open the locked things...

**If there was an error in console, put it here:**
```
There was no error...
```

**Comment by pop4959** [comment]
I can think of 2 possible issues off the top of my head:

- You have a conflicting plugin (try to remove all plugins and see if the problem persists)
- Your permissions are set incorrectly (check the wiki for permissions)

Also, be sure to update to 2.1.3, which is the latest version for 1.13.2

**Comment by pop4959** [comment]
Closing this issue due to lack of response.
