### ISSUE TITLE
Stop inherent limits

### ISSUE THREAD

**Issue by JohOply** [Tsuser1/Modern-LWC#109]
**LWC Version (/lwc admin version):** 2.1.2-dd8c289
**Server version (/version):** Spigot 1.13.2-b2148a

**Short five word summary of issue:** Limits set in limitsv2.yml weird inheritance

**Detailed description of problem:**
Hi there
I set limits per group in limitsv2.yml
I want to have very few protections for new players, then more when they upgrade

Right now, if I set "chest: 5" in first group, it will be limited.
But, if I do not redefine chest in second group, first group will be applied.

I think the best option would be to create a real permission for each created categories, like `lwc.limits.(name in the file)`, instead of have to use the name of the rank.
I think It will allow to set previous rank permission on false, which remove the issue

If something is not clear or if i'm wrong somewhere, please tell me

**If there was an error in console, put it here:**
https://pastebin.com/uss0uUCv
Screen: https://i.imgur.com/hpElt8t.png

PS: I will be away for some weeks, so if I do not answer right now, I will do later :)

**Comment by pop4959** [comment]
Can you link the entire limitsv2.yml file because just having a snippet is not too helpful here in determining if it's correct or not.

If your config is correct, that does sound like weird behaviour, and may be worth checking into.

**Comment by JohOply** [comment]
Uploaded here https://pastebin.com/uss0uUCv

**Comment by JohOply** [comment]
Added in dev builds https://github.com/pop4959/LWCX
