### ISSUE TITLE
[Feature Request] Add Factions support

### ISSUE THREAD

**Issue by animeavi** [Tsuser1/Modern-LWC#114]
Would it be possible to add support to check if the player placing a protection inside of the terrain has build permissions inside for it? I'd like to use LWC with Factions but as it is, you could go to someone else's faction and lock their doors with passwords etc.

This is the version of factions I use currently: https://github.com/drtshock/Factions

**Comment by pop4959** [comment]
Possibly! I'd imagine it could be added similarly to how WorldGuard and Towny are currently supported. I'll look into whether this is possible.

**Comment by pop4959** [comment]
Surprise! Basic support for Factions claims added in ade3c5d. You can grab the latest dev build and let me know if it's working appropriately.

**Comment by pop4959** [comment]
@animeavi I forgot to mention, there is a new configuration option for this: `core.factionCheck` needs to be set to `true` for this feature to work.
