### ISSUE TITLE
Minecraft 1.7.10 Unable to lock

### ISSUE THREAD

**Issue by qq839295616** [Tsuser1/Modern-LWC#116]
LWC Version: 1.9.6
Server version: Spigot 1.7.10
**Short five word summary of issue:** 
All items are packaged in the configuration.
Unable to lock
**Detailed description of problem:**
Unable to lock, the background did not prompt any errors.

**Comment by pop4959** [comment]
Thanks for the report. It looks like 1.9.6 only supports MC 1.8 or higher. This was a mistake on the plugin page. I apologise for the inconvenience.

You'll need an older version of LWC. I'm not sure where you would find this, however. Good luck!
