### ISSUE TITLE
Disable physics for locked armor stands?

### ISSUE THREAD

**Issue by Platinteufel** [Tsuser1/Modern-LWC#17]
**LWC Version (/lwc admin version):** 

2.1.0-dev-8f0b3a1/

**Server version (/version):** 

git-Spigot-2440e18-997d378 (MC: 1.13.1)

**Detailed description of problem:**

Maybe it is a good idea if locked armor stands can't get flushed away or be buried by destroying blocks below.

/Edit: I just saw that Entity locking is not highly supported now. So maybe this enhancement is for updates far in the future.

**Comment by Tsuser1** [comment]
Thank you for the suggestions, however as you noticed **we currently do not support entity locking**. We will definitely take a look at this when entity locking is revisited in a future update. Thank you!

**Comment by pop4959** [comment]
@Platinteufel It's not a bad suggestion, but please my last comments on #15 about our current stance on entity locking. I'll rephrase it below, with clarifications.

For the time being, we will only be providing **extremely minimal support for entity locking**. This means that we do not have plans to add new features, or make any guarantee to fix bugs related to entity locking. The reason being, that the previous maintainer (and author of entity locking) quit, and he has stated himself that entity locking is extremely buggy. As such, usage of this plugin's entity locking features is completely at your own risk. We are considering re-doing entity locking from scratch in the future, and at that point we would re-add official support for it.

My suggestion for this would be to perhaps find another plugin that disables physics?
