### ISSUE TITLE
loss of protections when updating

### ISSUE THREAD

**Issue by Mundo-Minecraft** [Tsuser1/Modern-LWC#18]
Version before updating protections: lwc 1.9.4 Spigot version 1.12.2 (last version 1.12.2)
Version used to update the database: lwc 2.1.0-dev Spigot 1.13.1 (last version)

Good afternoon

As you can see in the [photo](http://www.mundo-minecraft.com/wp-content/uploads/2018/08/lwc-mar9.jpg), all the existing protections of the user mar9 appear when writing / lwc admin find mar9 and if I look at their protections 233 appear occupied (the same as in 1.12.2) In that example photo id 11966 exists and with / lwc admin view 11966 shows the content of the chest, but when doing the same with the id (year 2016) 903 does not allow to see the content indicating that there is no such protection. And if I move to the coordinate the chest is unprotected. With the id 11966 all right and protected box. In short, the old protections appear with / lwc admin view but in practice they do not exist, with which they are newer everything is correct.

Greetings and thanks.

**Comment by pop4959** [comment]
I think you might have not read the updates section on the spigot resource page. Database upgrade from LWC 1.9.4 (1.12.2) to 2.x.x (1.13.x) is not supported yet. We don't recommend downloading or using dev builds unless you know what you are doing. They are unsafe to use and unintended for use in production.

**Comment by Mundo-Minecraft** [comment]
sorry I read it wrong, now I see that you have not yet allowed the conversion of 1.12.2. I'm using it on a test server.

Greetings and thanks for the plugin.

**Comment by pop4959** [comment]
Ah, good to know that it was only a test server. Some people have lost their databases and protections permanently due to not backing it up before loading in 1.13. There will be another update  when the initial (experimental) version with a database migrator for 1.12 -> 1.13 becomes available.

Thank you for your understanding. This update has been a lot of work for us, especially considering the previous author has left us.

**Comment by Mundo-Minecraft** [comment]
buff is that not making a copy of the database and putting in a production server the current versions is crazy. This week I'm starting to see plugins already quite stable.
I respect the LWC, all right the database works perfectly. He has respected all the protections.

Very good work, thank you very much.
