### ISSUE TITLE
double door auto open

### ISSUE THREAD

**Issue by karl-police** [Tsuser1/Modern-LWC#22]
So basically when you have a double door and cprivate it, it will automatically open up the other one, for some situation I would like to disable that.

Also the iron doors that got cprivated will also open up when rightclick, maybe also make it configureable, please?

**Comment by pop4959** [comment]
Good idea. Not sure why this wasn't configurable to begin with. I'll probably try to add this feature right after we are done releasing the full version of 2.1.0.

**Comment by Sikatsu** [comment]
Hmm, wasn't it possible before to configure whether you want to open iron doors on right click?

**Comment by pop4959** [comment]
@Sikatsu You're completely right about that. It's in the settings, but I just didn't realise it. Also didn't update this issue (whoops), but the real suggestion, as clarified by karl-police on the Discord server, was to add a flag which disables the door auto-open feature for specific doors. I'm not quite as sure whether this is a necessary change though.

**Comment by pop4959** [comment]
Not an issue. You can fully control doors in the `doors.yml` file.
