### ISSUE TITLE
Actionbar messages

### ISSUE THREAD

**Issue by Sikatsu** [Tsuser1/Modern-LWC#24]
I'd like to request a feature that allows you to switch the messages between chat and the actionbar.
This could either be a configuration in the core.yml or a command that allows the player to change their preference.

Sort of like the plugin ''McmmoAction''

**Comment by pop4959** [comment]
Yup, we talked about it on Discord. I'll look into this and see if it's possible for the next update.

**Comment by pop4959** [comment]
@Sikatsu @SimonOrJ Implemented in development build 41.
