### ISSUE TITLE
Iron Trapdoors Don't Click Open

### ISSUE THREAD

**Issue by roracle** [Tsuser1/Modern-LWC#26]
**LWC Version (/lwc admin version):** 
2.1.0
**Server version (/version):** 
1.13.1
**Short five word summary of issue:** 
Iron Trapdoors Don't Click Open
**Detailed description of problem:**
Iron doors work fine, but iron trapdoors do not.  They register okay, but they won't open on right click.
**If there was an error in console, put it here:**
```
<paste it here between the little tick marks> (NO CONSOLE OUTPUT)
```

**Comment by pop4959** [comment]
Bug confirmed. I'm going to try to fix this issue as soon as I get a chance. I'll try to notify you on here as soon as there is a development build available to address this.

**Comment by pop4959** [comment]
@roracle Fixed in development build 38.
