### ISSUE TITLE
failure with the iron trapdoor

### ISSUE THREAD

**Issue by Mundo-Minecraft** [Tsuser1/Modern-LWC#31]
**LWC Version (/lwc admin version):** 

Last LWC version 2.1.0 loaded

**Server version (/version):** 

This server is running CraftBukkit version git-Spigot-0ede7d0-228a5cd (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

**Short five word summary of issue:** 

failure to open protected iron_trapdoor

**Detailed description of problem:**

In the previous version of 1.12 you could open a metal trapdoor if it was protected with lwc and without the need for a lever, button ... etc. Defined in doors.yml. In the latest version for 1.13 does not allow it.

**If there was an error in console, put it here:**

no errors in console

Regards

**Comment by pop4959** [comment]
This sounds like the same issue as #26

**Comment by pop4959** [comment]
@Mundo-Minecraft Fixed in development build 38.

**Comment by Mundo-Minecraft** [comment]
I have downloaded the # 40, the metal trapdoor protection works fine.
But now it does not let protect "normal" wooden doors, any trapsdoor except metal and "normal" wooden fence gate.

Greetings and thanks.

**Comment by pop4959** [comment]
@Mundo-Minecraft It works perfectly development build 40. Check that your `core.yml` and `doors.yml` are correct. If you need to, delete/move them, and a correct one will be made next time you start your server.
