### ISSUE TITLE
Locking Item Frames

### ISSUE THREAD

**Issue by blarosen95** [Tsuser1/Modern-LWC#43]
Itemframes only lock for OPs. I can’t seem to find anything in the yaml that would fix this.

**Comment by pop4959** [comment]
Item frames are an entity, which requires permissions. OPs usually have all permissions by default. Read here: https://github.com/Tsuser1/Modern-LWC/wiki/Entity-Locking

Keep in mind we do not recommend using the current version of entity locking in any version of LWC. You are responsible for any database issues and bugs that occur from enabling it.
