### ISSUE TITLE
cnospam?

### ISSUE THREAD

**Issue by karl-police** [Tsuser1/Modern-LWC#46]
**LWC Version (/lwc admin version):** 2.1.0
**Server version (/version):** 1.13.1

**Short five word summary of issue:** cnospam, doesn't show, auto creation chest message

**Detailed description of problem:**
When /cnospam enabled you won't get notified on what you automatically lock, as example you place a chest, but you get notified when you destroy it, which is bad.

also cnospam should apply forever or something, otherwise you gotta change it everytime back to on.

**If there was an error in console, put it here:**
```
<paste it here between the little tick marks>
```

**Comment by pop4959** [comment]
[https://github.com/Tsuser1/Modern-LWC/wiki/Configuration](url)

@karl-police LWC seems to already support this. See the link above, at the "showNotices" and "showMyNotices" options.

**Comment by lifehome** [comment]
@karl-police I have fixed this issue in PR #49, but it seems @pop4959 is kinda busying this week, so you might have to wait till next week to see how things goes.

**Comment by pop4959** [comment]
@karl-police Fixed by @lifehome in development build 61. Breaking a protection by hand will no longer show the protection removal message if you have cnospam enabled.
