### ISSUE TITLE
No locale

### ISSUE THREAD

**Issue by 0xC1A551C** [Tsuser1/Modern-LWC#47]
**LWC Version (/lwc admin version):**  2.1.1
**Server version (/version):**  1.13.1

**Short five word summary of issue:** 
There is no locale files in the locale folder. Would like to end the messages to fit my server.

Thanks

**Comment by pop4959** [comment]
@0xC1A551C That folder is empty because it is meant for custom locales only. Built-in locales are accessible by changing the setting `locale` in `core.yml`. Read [https://github.com/Tsuser1/Modern-LWC/wiki/Custom-Locales](url)

Closing, since this is not an issue.
