### ISSUE TITLE
Problems updating MySQL database

### ISSUE THREAD

**Issue by Swede37** [Tsuser1/Modern-LWC#50]
**LWC Version (/lwc admin version):** Main plugin: 2.11-46e9fa0/
**Server version (/version):** git-Spigot-f6a273b-8ab46ff (MC: 1.13.1) (Implementing API version 1.13.1-R0.1-SNAPSHOT)

**Short five word summary of issue:** error updating MySQL database

**Detailed description of problem:**
completely removed the LWC folder to regen everything, restarted server.  Filled in the connection info, restarted server.  Looks like a new area "Blocks" has been added into the database, but I keep getting errors in console about "the name cannot be null"

**If there was an error in console, put it here:**
```
13.10 17:37:35 [Server] INFO Enabling LWC v2.1.1-46e9fa0
13.10 17:37:35 [Server] INFO Connecting to MySQL
13.10 17:37:35 [Server] INFO Performing database optimization for 1.13...
13.10 17:37:35 [Server] WARN java.lang.IllegalArgumentException: Name cannot be null
13.10 17:37:35 [Server] WARN at org.apache.commons.lang.Validate.notNull(Validate.java:192)
13.10 17:37:35 [Server] WARN at org.bukkit.Material.matchMaterial(Material.java:2807)
13.10 17:37:35 [Server] WARN at org.bukkit.Material.matchMaterial(Material.java:2792)
13.10 17:37:35 [Server] WARN at com.griefcraft.cache.BlockCache.addBlock(BlockCache.java:168)
13.10 17:37:35 [Server] WARN at com.griefcraft.sql.PhysDB.doUpdateModernLWC(PhysDB.java:2192)
13.10 17:37:35 [Server] WARN at com.griefcraft.sql.PhysDB.load(PhysDB.java:414)
13.10 17:37:35 [Server] WARN at com.griefcraft.lwc.LWC.load(LWC.java:1685)
13.10 17:37:35 [Server] WARN at com.griefcraft.lwc.LWCPlugin.onEnable(LWCPlugin.java:282)
13.10 17:37:35 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
13.10 17:37:35 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:339)
13.10 17:37:35 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
13.10 17:37:35 [Server] WARN at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:431)
13.10 17:37:35 [Server] WARN at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:345)
13.10 17:37:35 [Server] WARN at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:214)
13.10 17:37:35 [Server] WARN at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:702)
13.10 17:37:35 [Server] WARN at java.lang.Thread.run(Thread.java:748)
```

**Comment by Tsuser1** [comment]
Please provide the full version string from `/lwc admin version`.

**Comment by pop4959** [comment]
@Swede37 What version are you upgrading from, and what kind of database are you using for MySQL? If you have a modified core.yml please link us to that as well.

The database upgrade for 1.13 was tested to work, upgrading from either LWC 1.9.4 or 2.0.7, using both SQLite and MySQL.

**Comment by Swede37** [comment]
What I was using on 1.12.2 was 
``13.10 19:35:30 [Server] INFO Main plugin: 2.0.7/ ``

I'm using a MySQL setup on a host with PHPmyadmin.  I really don't know a lot about databases, so if you can point me in the right direction I can give you more info about that?

I had copied over *everything* from the open server to create a test server. I even recreated the database with all the same files, (a completely separate database) through the option in Multicraft provided by my host, and uploaded all the same files I had on the 1.12.2 server for test purposes.

The core.yml will be the default generated when I deleted my original LWC folder, all that I changed was to set it to Mysql.

**Comment by Swede37** [comment]
A copy of my core.yml
https://pastebin.com/Z9RCLTNh

**Comment by pop4959** [comment]
@Swede37 There shouldn't be any issues upgrading from that version. Are your MySQL settings correct? If the new copy you made has a different prefix, make sure you change it there. Also, SSL is set to false by default in 2.1.x so you do not have to set that yourself. You may want to check with your host if the other settings you have provided appear to be correct.

Also, it may help to show a screenshot of the first page or so of entries in your `protections` and `blocks` table pre and post upgrade. Also worth checking is if there are any entries in the blockName column that contain NULL.

**Comment by Swede37** [comment]
just on first view, I have a LOT of entries in the blockName column that contain NULL on the 1.13.1 database
![lwc protections 1 13 1](https://user-images.githubusercontent.com/27977842/46917141-f8b65180-cf88-11e8-99c4-927b910f2e7e.png)

**Comment by pop4959** [comment]
Ah I see, it was as I figured. I think the mixed nulls in your database are throwing off the database migrator in 2.1.x. How did your database get into this state? Did you switch back and forth between using different versions of MC/LWC several times?

Anyways, I think you have three choices. You can either make a fresh database and lose your current protections, manually update your database (it isn't as much work as it sounds), or somehow give me access to a copy of the database so that I can try to make a fix that addresses this issue. If one of those last 2 options sound good, please reach out to me on the Discord support channel.

**Comment by Swede37** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Contacted you on Discord :)                                                                                                                                                                        Sent via the BlackBerry Hub for Android                                                                                                                                                                           From: notifications@github.comSent: October 15, 2018 12:02 AMTo: Modern-LWC@noreply.github.comReply to: reply@reply.github.comCc: fepay1998@gmail.com; mention@noreply.github.comSubject: Re: [Tsuser1/Modern-LWC] Problems updating MySQL database (#50)  Ah I see, it was as I figured. I think the mixed nulls in your database are throwing off the database migrator in 2.1.x. How did your database get into this state? Did you switch back and forth between using different versions of MC/LWC several times?
Anyways, I think you have three choices. You can either make a fresh database and lose your current protections, manually update your database (it isn't as much work as it sounds), or somehow give me access to a copy of the database so that I can try to make a fix that addresses this issue. If one of those last 2 options sound good, please reach out to me on the Discord support channel.

**Comment by pop4959** [comment]
I've talked with Swede on the Discord, and this seems to have been an issue regarding the now unsupported 2.0.7 version leaving the database in an inconsistent state after its upgrade process. This is a known issue, and one of the reasons why this version is not supported anymore.

For anyone reading this: I highly suggest not using any 2.0.x version, and instead only use 1.9.4 for pre-1.13, and 2.1.0+ for 1.13+.
