### ISSUE TITLE
Request: add option to enable check type of protected blocks on chunk load.

### ISSUE THREAD

**Issue by Gerolfing** [Tsuser1/Modern-LWC#56]
There are situations when block has changed or no longer exists while protection is still there. For example: new generation of old chunks, rollback with log block or /replace command. I thought about this and it would be nice to have an option for some sort of cheking protected blocks on chunk load to let LWC know that initially protected block is still there or gone. If initially protected block is not there that protection of that block vanishes.

**Comment by pop4959** [comment]
@Gerolfing Check the wiki; you probably want to use lwc admin cleanup. It's only available as a command because it is an expensive operation. You do not want to run it on chunk load. It would almost certainly cause an unacceptable amount of lag.

**Comment by Gerolfing** [comment]
@pop4959  Thanks for your answer. With single admin command it's even better.
