### ISSUE TITLE
Player UUID shows up when adding a player to private chest, sign, exc.

### ISSUE THREAD

**Issue by pjt0720** [Tsuser1/Modern-LWC#58]
**LWC Version (/lwc admin version):**
2.1.1
**Server version (/version):**
1.13.2

**Short five word summary of issue:**
Player UUID shows up.

**Detailed description of problem:**
When you do /cmodify <playername> to add a player to a lock, the players Name and UUID shows up in chat when the player is added. The only person who can see the UUID is the player that added the other player.

I was wondering if there is a way to make it so the player UUID does not show up in chat and only displays the Name?

**If there was an error in console, put it here:**
```
N/A
```

**Comment by pjt0720** [comment]
Thank you very much for looking into this and fixing it. I was just a little worried that players would have the ability to see another players unique UUID. I am sure no one can do anything with it, but the possibility is there.

**Comment by pop4959** [comment]
There is no danger that comes from people viewing another's UUID. You can even look them up online (for example the namemc website). I'm only considering removing it from cmodify to prevent some chat spam.

**Comment by pop4959** [comment]
The UUID will no longer be shown in chat when using cmodify, as of the latest development build.
