### ISSUE TITLE
Update WorldGuard plugin module with new breaking WG changes - BlockVector3.

### ISSUE THREAD

**Issue by mibby** [Tsuser1/Modern-LWC#64]
WorldEdit made some changes to a new BlockVector system. WG plugin module needs to be updated to support it.

i.e. https://github.com/Brokkonaut/LWCEntityLocking/commit/e59b35593acfdea17fbefb16f250a1d7cc1c8bb7

**Comment by pop4959** [comment]
Thanks for notifying us about the change. We will definitely need to make similar code changes. Although, it might be a good idea to add backwards compatibility for versions of WorldGuard 7 prior to this breaking change, since it might otherwise catch a lot of server owners by surprise.

**Comment by pop4959** [comment]
Should be fixed in the latest development build.
