### ISSUE TITLE
Is this problem? compare int and Integer variable

### ISSUE THREAD

**Issue by falconws** [Tsuser1/Modern-LWC#65]
https://github.com/Tsuser1/Modern-LWC/blob/4973f9806e85f27da13aa2c45201f45476867f18/src/main/java/com/griefcraft/cache/BlockCache.java#L121

nextId is `int` and materialId is `Integer`.
Is this compare correct?

**Comment by pop4959** [comment]
It should be fine due to Java's autoboxing feature. See [https://docs.oracle.com/javase/tutorial/java/data/autoboxing.html](https://docs.oracle.com/javase/tutorial/java/data/autoboxing.html)

**Comment by falconws** [comment]
Thanks for the response.
I understand it! close issue....
