### ISSUE TITLE
Jenkins down.

### ISSUE THREAD

**Issue by andrewkm** [Tsuser1/Modern-LWC#67]
https://ci.zeusmainframe.ml/job/modern-lwc/job/dev-builds/

**Comment by Tsuser1** [comment]
The fact that you reported this the very minute services went down is quite a coincidence. We are working on restoring services.

**Comment by Tsuser1** [comment]
Problem has been isolated to our CDN. Please be patient while problems are resolved.

**Comment by andrewkm** [comment]
Lmao did you just low-key say I’m DDoSing some random Jenkins ...

If that’s not what you meant all good. Thanks for the response :)

**Comment by Tsuser1** [comment]
No, I’m just saying your timing was impeccable.
