### ISSUE TITLE
Cannot compile latest dev builds using the new WG vector system.

### ISSUE THREAD

**Issue by andrewkm** [Tsuser1/Modern-LWC#68]
Dev branch:
https://pastebin.com/raw/CBP3J1TP

**Comment by andrewkm** [comment]
Got it working with local library on my end.

**Comment by pop4959** [comment]
@andrewkm Dev builds should compile now. The issue has resolved itself. We might put in some additional effort later to make sure that future breakage is less likely to occur, but for now it works as before.

**Comment by me4502** [comment]
I ended up working out what it was - the CodeMC repo was incorrectly reporting itself as the WorldEdit repo, and the index was being downloaded and cached from there as it was marked with a much higher build number than the real repo.

Even if the repo wasn't being used in the project you were actually compiling, it was still in the maven cache and causing issues.

**Comment by pop4959** [comment]
Wow, what a coincidence. The elmaker repo went down around the same time, so we thought it was an issue with that instead. If it was actually the CodeMC repo, that explains why we weren't having any luck trying to fix this.
