### ISSUE TITLE
Right click on protected doors aren't working

### ISSUE THREAD

**Issue by lifehome** [Tsuser1/Modern-LWC#76]
**LWC Version (/lwc admin version):** 2.1.2 4d34ea2
**Server version (/version):** Paper 1.13.2-R0.1 b474

**Short five word summary of issue:** Right clicks just won't open protected doors.

**Detailed description of problem:**
To replicate, simply create a protection on iron doors, and right click to it.

**Comment by pop4959** [comment]
Interesting issue, I don't think that door behaviour was changed plugin-side except for when initially updating to 1.13. Perhaps CraftBukkit or Paper received some updates that have affected this. I'll try to investigate it more tomorrow, but if you are able to do some testing with prior versions of Paper/LWC it will help.

**Comment by pop4959** [comment]
Should be fixed in the latest development build.
