### ISSUE TITLE
[WIP] Economy Modules Overhaul

### ISSUE THREAD

**Issue by lifehome** [Tsuser1/Modern-LWC#77]
Hello everyone,

As of Modern LWC release 2.1.2, I have reintroduced the basic economy features that were written by @Hidendra back in the good old days. And to be honest the codes are pretty old and needs an overhaul, to adopt both the changes made on Modern LWC, as well as Vault implementations and economy concepts.

Note: This should not be blocking future releases.

Main Tasks:
- [x] Reintroduce economy module before 2.1.2 release build
- [ ] Rewrite the whole module
  - [ ] `[BUG]` Spectators with admin permission node will get charged `onProtectionInteract`
  - [ ] `[BUG]` Players inspecting protection with CoreProtect/Prism will get charged `onProtectionInteract`
  - [ ] `[BUG]` Players crouching and interact with protection will get charged
  - [ ] `[Rewrite]` Use bukkit-events instead of LWC internal events (see #21)
  - [ ] `[TODO]` Extract strings from hardcoded to `strings.yml`
  - [ ] `[TODO]` Writeback configuration items into `config.yml`

Moreover, the economy idea is still under development, one major discussion is to decide whether the "Bank" feature should stay. The idea is that, players get charged and refunded upon interacting with protection, but where should the money comes and go? Please feel free to comment below and unless a consensus have came up afterward, the "bank" feature will stay disabled but not removed. (Means it would require explicit configurations before using it)

Warm Reminder: If you're going to discuss on this, please do elaborate instead of just posting your stance with one or two word.

Regards,
Ivan

**Comment by pop4959** [comment]
I appreciate how thorough this issue is, feel free to implement any of the bug fixes as is reasonable. I'm going to close this issue though, since this is a stagnant WIP that has not been touched for well over half a year. Keep in mind that the modules are likely not going to be going, due to how deeply baked into the plugin it is, and serves as an API to external plugins.
