### ISSUE TITLE
Worldguard error

### ISSUE THREAD

**Issue by timr2000** [Tsuser1/Modern-LWC#78]
**LWC Version (/lwc admin version):** 
2.1.2-dd8c289
**Server version (/version):** 
http://prntscr.com/m0u3rj
**Short five word summary of issue:** 
When placing a chest it gives a PLAYER_INTERACT error..
**Detailed description of problem:**

**If there was an error in console, put it here:**
```
https://pastebin.com/wbKk6upZ
```

**Comment by pop4959** [comment]
@timr2000 Please read the patch notes before reporting an error. LWC 2.1.2 requires the latest version of WorldGuard. Update it or use LWC 2.1.1 for outdated versions of WorldGuard.
