### ISSUE TITLE
Version 2.1.0 - The Fixer-upper Update

### ISSUE THREAD

**Issue by Tsuser1** [Tsuser1/Modern-LWC#8]
Hello everyone, and welcome to the official continuation of Modern LWC, this is our 2.1.0 update roadmap:

- [x] Setup Jenkins for Modern LWC
- [x] Setup Discord for Modern LWC
- [x] Rewrite the latest database handler to fix a multitude of strange issues.
- [x] Begin plugin optimizations.

**Comment by pop4959** [comment]
Most of the big issues are taken care of. If there are no major game-breaking bugs in the plugin, I think the full version of 2.1.0 will be ready by this weekend. At this point, I would say it is relatively safe to use the latest development builds, but server owners should use caution.

**Comment by pop4959** [comment]
It's done. Get it on the build server or on the spigot resource page (soon). Enjoy, people!
