### ISSUE TITLE
Doesn't work correctly on MC Version 1.13.2

### ISSUE THREAD

**Issue by MasterCevin** [Tsuser1/Modern-LWC#87]
Plugin version: LWC v4.4.0 (b881) (July 11, 2013)
Server version: CraftBukkit version git-Spigot-e5e5c7c-c24abab (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

Could not lock any Blocks

If i run the comman /cpublic or /cprivate and I punch a block it gives the following error in the Minecraft-Chat:
[LWC] Internal error. Notify an admin immediately. :PLAYER_INTERACT
I can't lock any Blocks (doesn't do that automaticly or with the commands)

Log: [latest (1).log](https://github.com/Tsuser1/Modern-LWC/files/2890074/latest.1.log)

**Comment by MasterCevin** [comment]
Sorry for the "...(1)" at the end of the filenames.
I just opened a new issue, because i opened another issue before on the wrong github page.

**Comment by MasterCevin** [comment]
I also stoped the server multiple times and deleted the /LWC folder, restarted the Server and it Didn't worked at all.
Same errors.

**Comment by pop4959** [comment]
@MasterCevin 

You should read your log. The issue appears obvious:
`[17:41:20] [Server thread/ERROR]: Error occurred while enabling LWC v4.4.0 (b881) (July 11, 2013) (Is it up to date?)`

You should not be using a version of LWC that is 6 years old. Download the latest stable version on the Spigot plugin catalog: [https://www.spigotmc.org/resources/modern-lwc-continuation-of-lwc.2162/history](https://www.spigotmc.org/resources/modern-lwc-continuation-of-lwc.2162/history)

I recommend also deleting your LWC folder, so that a new one is freshly created. Backwards compatibility is not guaranteed nor supported with the version you are trying to use.

**Comment by MasterCevin** [comment]
wait, I’ll upload the plugin on the server, delete the LWC folder, restart and upload the log. Wait just 15 min.

**Comment by pop4959** [comment]
I removed your server files from the original post, as we do not need them. I've updated it with the correct information. Closing this issue now.

**Comment by MasterCevin** [comment]
Hey, it also doesn't work
Log: [latest.log](https://github.com/Tsuser1/Modern-LWC/files/2891538/latest.log)

**Comment by mbax** [comment]
In that log is a call to PermissionsEx, but PEX isn't actually on your server? This feels like a problem in your (inexplicably premium) permissions plugin to me.

**Comment by MasterCevin** [comment]
On my old Spigot 1.8 server it worked with the permission plugin, but i can try to use PEX.

**Comment by pop4959** [comment]
@MasterCevin The solution is to update all of your plugins.

**Comment by Tsuser1** [comment]
Look, I’m just going to be real here. If there were such a glaring issue with MLWC, why hasn’t it shown up before in the past two months? In all likelyhood, it is more than likely your unique server configuration. Replicate the issue with no plugins other than the *latest* version of MLWC and the *latest* Spigot build and we’ll listen.

**Comment by mbax** [comment]
"but i can try to use PEX"

I wasn't saying to use PEX. I'm saying that it looks like UltraPermissions is pretending to be PEX in a way that's broken.

**Comment by mbax** [comment]
Either way, though, you should use LuckPerms at this point.

**Comment by MasterCevin** [comment]
Hey, it was the permissions plugin.
I used PEX for a quick test and it worked.
Thank you all for your help :-)

**Comment by Tsuser1** [comment]
Please note that PEX is old, we recommend LuckPerms at this time.

**Comment by MasterCevin** [comment]
I'll try to use it :D
