### ISSUE TITLE
[Bug] Player kick

### ISSUE THREAD

**Issue by SiroQ** [Tsuser1/Modern-LWC#91]
**LWC Version (/lwc admin version):** 2.1.1-46e9fa0
**Server version (/version):** This server is running Paper version git-Paper-521 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)

**Short five word summary of issue:** 
Shulker box in shulker box causes player kick(May leads to server crash)

**Detailed description of problem:**
Putting Shulker boxes in shulker box(and repeat it some times), client will be kicked.
and it can be done by magnet flag, so LWC should ignore shulker box in magnet flag.
![image](https://user-images.githubusercontent.com/26434739/54082297-7161e400-4356-11e9-94d9-121917fa46c0.png)

**Comment by Tsuser1** [comment]
You are right, this should not be possible. This poses a significant stability risk (known protocol initiation), this is actually a method used to crash servers.

**Comment by pop4959** [comment]
Please download the latest development build. It should be fixed now.
