### ISSUE TITLE
Major TPS Drop From LWCBlockListener When Water is Dispensed by Numerous Dispensers 

### ISSUE THREAD

**Issue by SurvivalQuest** [Tsuser1/Modern-LWC#94]
LWC 2.1.3-dev-09f368f
Paper-568 (MC: 1.13.2)
Config: https://pastebin.com/KakM0nCU

Major TPS Drop From LWCBlockListener When Water is Dispensed by Numerous Dispensers

If a player makes a passive mob farm that utilizes over 20 dispensers triggered by a redstone clock to dispense water every ~10 seconds, the server's TPS drops from 20 to around 10. When the redstone clock is stopped the TPS goes back up to 20 and everything is back to normal.
When looking at the timings report, the LWCBlockListener is spending a lot of time under Scheduled Fluids Ticking. No errors in console.

https://timings.aikar.co/?id=cba77bc664ff4|ff486440d7a5d243c5f

Minecraft::world - Scheduled Fluids - Ticking
---> LWC::Event: c.g.l.LWCBlockListener (BlockFromToEvent)

**Comment by pop4959** [comment]
It looks like someone missed a simple check in the code to make sure that the database is only being queried when water might be flowing into (and destroying) a protect-able block. This could cause a lot of the lag you are seeing. I've pushed a dev build that should fix this. Try it out and let me know if that causes a difference for you.

**Comment by SurvivalQuest** [comment]
That was super fast. I just threw it on and will test it out. Thank you!

**Comment by SurvivalQuest** [comment]
Haven't had any major lag yet with water. I'll come back if I notice it doing it again.

**Comment by pop4959** [comment]
It shouldn't. Thanks for letting me know, closing this now.
