### ISSUE TITLE
LWC Crashed Paper Server?

### ISSUE THREAD

**Issue by SurvivalQuest** [Tsuser1/Modern-LWC#99]
**LWC Version: 2.1.3-dev-288b1bf  Build 11** 
**Server version: 1.13.2 Paper-600** 

Server crashed randomly and LWC appears in the thread dump. There are no lwc commands entered by anyone before the crash.
Hope this pastebin can help investigate if there's an issue with LWC.
https://pastebin.com/9EbcDrR0

**Comment by pop4959** [comment]
It looks like it halted while waiting for a response on your database. I'm assuming you're using a MySQL server and for whatever reason your server was no longer able to connect to it. If that is the case, this isn't much of an LWC issue, but something you want to look into fixing on your end.
